### ISSUE TITLE
After some time running, new events are not collected

### ISSUE THREAD

**Issue by max-rocket-internet** [splunk/fluent-plugin-kubernetes-objects#9]
I think this is the same issue as https://github.com/splunk/fluent-plugin-kubernetes-objects/issues/5

It happens on all of our clusters. Logging stops after 1-3 hours.

Here's the Dockerfile for our fluentd container: https://github.com/deliveryhero/k8s-event-logger/blob/master/Dockerfile

And here's our `fluent.conf`: https://github.com/deliveryhero/k8s-event-logger/blob/master/conf/fluent.conf

Please note that setting an k8s API server flags is not an option as we are using AWS EKS. It would also not be an option for anyone using a managed k8s service, e.g. GKE, AKS etc.

**Comment by max-rocket-internet** [comment]
https://github.com/splunk/fluent-plugin-kubernetes-objects/pull/13 was proposed but another PR was merged instead: https://github.com/splunk/fluent-plugin-kubernetes-objects/pull/21
And released in version `1.1.1`: https://github.com/splunk/fluent-plugin-kubernetes-objects/pull/24

But for me, it still stops processing new events.

Here's my config:

```
2019-04-02 08:30:36 +0000 [info]: parsing config file is succeeded path="/fluentd/etc/fluent.conf"
2019-04-02 08:30:40 +0000 [warn]: both of Plugin @id and path for <storage> are not specified. Using on-memory store.
2019-04-02 08:30:40 +0000 [info]: using configuration file: <ROOT>
  <source>
    @type kubernetes_objects
    kubernetes_url "https://172.20.0.1:443"
    ca_file "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
    <watch>
      resource_name "events"
      namespace "default"
    </watch>
    <watch>
      resource_name "events"
      namespace "kube-system"
    </watch>
  </source>
  <format>
    @type stdout
    output_type json
  </format>
  <match **>
    @type stdout
    format json
    <format>
      @type json
    </format>
  </match>
</ROOT>
```

Startup messages:

```
2019-04-02 08:30:40 +0000 [info]: starting fluentd-1.4.1 pid=7 ruby="2.3.3"
2019-04-02 08:30:40 +0000 [info]: spawn command to main:  cmdline=["/usr/bin/ruby2.3", "-Eascii-8bit:ascii-8bit", "/fluentd/vendor/bundle/ruby/2.3.0/bin/fluentd", "-c", "/fluentd/etc/fluent.conf", "-p", "/fluentd/plugins", "--gemfile", "/fluentd/Gemfile", "--under-supervisor"]
2019-04-02 08:30:44 +0000 [info]: gem 'fluent-plugin-kubernetes-objects' version '1.1.1'
2019-04-02 08:30:44 +0000 [info]: gem 'fluentd' version '1.4.1'
2019-04-02 08:30:44 +0000 [info]: adding match pattern="**" type="stdout"
2019-04-02 08:30:44 +0000 [info]: adding source type="kubernetes_objects"
2019-04-02 08:30:49 +0000 [warn]: #0 both of Plugin @id and path for <storage> are not specified. Using on-memory store.
2019-04-02 08:30:49 +0000 [warn]: section <format> is not used in <ROOT>
2019-04-02 08:30:49 +0000 [warn]: section <format> is not used in <ROOT>
2019-04-02 08:30:49 +0000 [info]: #0 starting fluentd worker pid=12 ppid=7 worker=0
2019-04-02 08:30:49 +0000 [info]: #0 fluentd worker is now running worker=0
```

Some events are printed but nowhere near the volume of all events happening in the cluster. A simple test is to just compare the output from fluentd with the output from `kubectl get events --watch` and then simply delete a pod.

**Comment by dtregonning** [comment]
Ok thanks @max-rocket-internet - thats not great. we will review the amount of events coming through and update this plugin again with the original fix.

**Comment by chaitanyaphalak** [comment]
Fixed as part of https://github.com/splunk/fluent-plugin-kubernetes-objects/pull/34

**Comment by v1r7u** [comment]
1. I have this problem with version `1.1.2`. After deployment it watches new events for a while and then just stops ingesting new data: 
![image](https://user-images.githubusercontent.com/1583399/65597324-28434b80-df99-11e9-99a8-054f1225384b.png)

I tried to restart it several times - the same effect.

2. Also, I suspect it does not receive all the events by some reason. I tried to compare events in
- `kubectl get events --all-namespaces`
- Azure ContainerInsights
- this plugin
the first one has the most data, the second has 3-5 times more data than the third one.

If you need to get more details - please, let me know

**Comment by fradee** [comment]
Issue did not fixed https://github.com/splunk/fluent-plugin-kubernetes-objects/issues/44
